"""Python code generator.

This module implements a code generator that translates AST nodes
into Python source code.
"""

from .base import CodeGenerator


class PythonGenerator(CodeGenerator):
    """Generate Python code from AST.

    This generator produces Python 3 code with type hints.
    Generates executable code without if __name__ == "__main__" guard
    since output is meant for direct execution, not as an importable module.

    Example output:
        '''Generated by mini_compiler from program test.'''

        a: int
        b: int

        a = 5
        b = (a + 10)
        print(b)
    """

    def visit_program(self, node):
        """Generate Python program structure.

        Format:
        - Docstring with program name
        - Variable declarations with type hints
        - Statements

        Note: No if __name__ == "__main__" guard since this is
        compiler-generated code meant for direct execution.
        """
        # Docstring header
        self._emit(f'"""Generated by mini_compiler from program {node.name}."""')
        self._emit_blank()

        # Declarations
        if node.declarations:
            for decl in node.declarations:
                decl.accept(self)
            self._emit_blank()

        # Statements
        for stmt in node.statements:
            stmt.accept(self)

    def visit_declaration(self, node):
        """Generate Python variable declarations.

        In Python, we use type hints: variable_name: int
        """
        for name in node.names:
            self._emit(f"{name}: int")

    def visit_assignment(self, node):
        """Generate Python assignment statement.

        Format: variable = expression
        """
        expr_code = node.expression.accept(self)
        self._emit(f"{node.variable} = {expr_code}")

    def visit_print(self, node):
        """Generate Python print statement.

        Formats:
        - print(variable)
        - print(f"label{variable}")  # if label present
        """
        if node.label:
            # Has label like '"value=",'
            # Extract just the text between quotes
            label = node.label.replace('"', "").replace(",", "")
            self._emit(f'print(f"{label}{{{node.variable}}}")')
        else:
            self._emit(f"print({node.variable})")

    def visit_binary_expression(self, node):
        """Generate Python binary expression.

        Format: (left operator right)
        Parentheses ensure correct precedence.

        Returns:
            String with expression code.
        """
        left_code = node.left.accept(self)
        right_code = node.right.accept(self)
        return f"({left_code} {node.operator} {right_code})"

    def visit_number(self, node):
        """Generate Python number literal.

        Returns:
            String representation of the number.
        """
        return str(node.value)

    def visit_variable(self, node):
        """Generate Python variable reference.

        Returns:
            Variable name string.
        """
        return node.name
