"""Integration tests for the mini compiler.

These tests exercise the entire compilation pipeline from source to executable code.
"""

import pytest
from pathlib import Path
from mini_compiler.core.preprocessor import Preprocessor
from mini_compiler.core.language import Language
from mini_compiler.core.parser import Parser
from mini_compiler.codegen.python_gen import PythonGenerator
from mini_compiler.utils.constants import PARSING_TABLE, SYMBOL_INDICES, RESERVED_WORDS


class TestEndToEndCompilation:
    """Test complete compilation pipeline."""
    
    def test_compile_simple_program(self, tmp_path):
        """Test complete compilation of simple program."""
        # Create source file
        source_file = tmp_path / "simple.src"
        source_file.write_text("""
            program abc;
            var a : integer ;
            begin
                a = 5 ;
                print ( a ) ;
            end
        """)
        
        # Preprocess
        preprocessor = Preprocessor()
        tokens = preprocessor.process_file(str(source_file))
        
        # Parse
        language = Language('Program', PARSING_TABLE, SYMBOL_INDICES, RESERVED_WORDS)
        parser = Parser(language, tokens)
        result = parser.parse_with_ast()
        
        assert result.accepted
        assert result.ast is not None
        
        # Generate code
        generator = PythonGenerator()
        code = generator.generate(result.ast)

        # Verify code is valid and runs
        assert 'Generated by mini_compiler' in code
        exec(code)  # Should not raise
    
    def test_compile_complex_expression(self, tmp_path):
        """Test compilation of program with complex expressions."""
        source_file = tmp_path / "complex.src"
        source_file.write_text("""
            program calc;
            var a, b, c : integer ;
            begin
                a = 10 ;
                b = 5 ;
                c = ( a + b ) * 2 ;
                print ( c ) ;
            end
        """)
        
        # Full pipeline
        preprocessor = Preprocessor()
        tokens = preprocessor.process_file(str(source_file))
        
        language = Language('Program', PARSING_TABLE, SYMBOL_INDICES, RESERVED_WORDS)
        parser = Parser(language, tokens)
        result = parser.parse_with_ast()
        
        assert result.accepted
        
        generator = PythonGenerator()
        code = generator.generate(result.ast)
        
        # Execute and capture output
        from io import StringIO
        import sys
        
        old_stdout = sys.stdout
        sys.stdout = StringIO()
        
        try:
            exec(code)
            output = sys.stdout.getvalue()
        finally:
            sys.stdout = old_stdout
        
        # Should print 30 (result of (10 + 5) * 2)
        assert '30' in output
    
    def test_compile_with_comments(self, tmp_path):
        """Test that comments are properly removed during compilation."""
        source_file = tmp_path / "commented.src"
        source_file.write_text("""
            program abc;
            (* This is a comment *)
            var a : integer ;
            begin
                a = 42 ; (* inline comment *)
                print ( a ) ;
            end
        """)
        
        preprocessor = Preprocessor()
        tokens = preprocessor.process_file(str(source_file))
        
        # Comments should be removed
        assert 'comment' not in ' '.join(tokens).lower()
        
        # Should still compile successfully
        language = Language('Program', PARSING_TABLE, SYMBOL_INDICES, RESERVED_WORDS)
        parser = Parser(language, tokens)
        result = parser.parse_with_ast()
        
        assert result.accepted
    
    def test_semantic_analysis_integration(self, tmp_path):
        """Test semantic analysis in integration."""
        source_file = tmp_path / "undeclared.src"
        source_file.write_text("""
            program bad;
            var a : integer ;
            begin
                b = 10 ;
                print ( b ) ;
            end
        """)
        
        preprocessor = Preprocessor()
        tokens = preprocessor.process_file(str(source_file))
        
        language = Language('Program', PARSING_TABLE, SYMBOL_INDICES, RESERVED_WORDS)
        parser = Parser(language, tokens)
        result = parser.parse_with_semantics()
        
        # Syntax should be valid
        assert result.accepted
        
        # But semantic errors should be detected
        assert result.semantic_errors.has_errors()
    
    def test_case_insensitive_compilation(self, tmp_path):
        """Test that case-insensitive input compiles correctly."""
        source_file = tmp_path / "uppercase.src"
        source_file.write_text("""
            Program ABC;
            Var A : Integer ;
            Begin
                A = 5 ;
                Print ( A ) ;
            End
        """)
        
        preprocessor = Preprocessor()
        tokens = preprocessor.process_file(str(source_file))
        
        # All should be lowercase
        assert all(t == t.lower() or not t.isalpha() for t in tokens)
        
        language = Language('Program', PARSING_TABLE, SYMBOL_INDICES, RESERVED_WORDS)
        parser = Parser(language, tokens)
        result = parser.parse_with_ast()
        
        assert result.accepted


class TestExampleFiles:
    """Test compilation of example files."""
    
    def test_example1_compiles(self):
        """Test that example1.src compiles successfully."""
        preprocessor = Preprocessor()
        tokens = preprocessor.process_file('examples/valid/example1.src')
        
        language = Language('Program', PARSING_TABLE, SYMBOL_INDICES, RESERVED_WORDS)
        parser = Parser(language, tokens)
        result = parser.parse_with_ast()
        
        assert result.accepted
        assert result.ast is not None
        
        # Generate and verify Python code
        generator = PythonGenerator()
        code = generator.generate(result.ast)
        
        compile(code, '<string>', 'exec')  # Should not raise
    
    def test_simple_compiles(self):
        """Test that simple.src compiles successfully."""
        preprocessor = Preprocessor()
        tokens = preprocessor.process_file('examples/valid/simple.src')
        
        language = Language('Program', PARSING_TABLE, SYMBOL_INDICES, RESERVED_WORDS)
        parser = Parser(language, tokens)
        result = parser.parse_with_ast()
        
        assert result.accepted
    
    def test_invalid_example_fails(self):
        """Test that invalid examples are properly rejected."""
        preprocessor = Preprocessor()
        tokens = preprocessor.process_file('examples/invalid/missing_semicolon.src')
        
        language = Language('Program', PARSING_TABLE, SYMBOL_INDICES, RESERVED_WORDS)
        parser = Parser(language, tokens)
        result = parser.parse()
        
        assert result.accepted is False
    
    def test_undeclared_var_example(self):
        """Test that undeclared variable example detects semantic errors."""
        preprocessor = Preprocessor()
        tokens = preprocessor.process_file('examples/invalid/undeclared_variable.src')
        
        language = Language('Program', PARSING_TABLE, SYMBOL_INDICES, RESERVED_WORDS)
        parser = Parser(language, tokens)
        result = parser.parse_with_semantics()
        
        # Syntax OK, semantics not OK
        assert result.accepted
        assert result.semantic_errors.has_errors()
