"""Tests for code generation."""

import pytest

from mini_compiler.codegen.python_gen import PythonGenerator
from mini_compiler.core.parser import Parser


class TestPythonCodeGeneration:
    """Test suite for Python code generation."""

    def test_generate_simple_program(self, language, simple_valid_tokens):
        """Test generating Python code for simple program."""
        parser = Parser(language, simple_valid_tokens)
        result = parser.parse_with_ast()

        assert result.accepted
        assert result.ast is not None

        generator = PythonGenerator()
        code = generator.generate(result.ast)

        assert "Generated by mini_compiler" in code
        assert "a: int" in code
        assert "a = 5" in code
        assert "print(a)" in code

    def test_generate_multiple_variables(self, language):
        """Test generating code for multiple variable declarations."""
        tokens = [
            "program",
            "abc",
            ";",
            "var",
            "a",
            ",",
            "b",
            ",",
            "c",
            ":",
            "integer",
            ";",
            "begin",
            "a",
            "=",
            "1",
            ";",
            "end",
        ]
        parser = Parser(language, tokens)
        result = parser.parse_with_ast()

        generator = PythonGenerator()
        code = generator.generate(result.ast)

        assert "a: int" in code
        assert "b: int" in code
        assert "c: int" in code

    def test_generate_arithmetic_expression(self, language):
        """Test generating code for arithmetic expressions."""
        tokens = [
            "program",
            "abc",
            ";",
            "var",
            "a",
            ",",
            "b",
            ",",
            "c",
            ":",
            "integer",
            ";",
            "begin",
            "c",
            "=",
            "a",
            "+",
            "b",
            ";",
            "end",
        ]
        parser = Parser(language, tokens)
        result = parser.parse_with_ast()

        generator = PythonGenerator()
        code = generator.generate(result.ast)

        assert "c = (a + b)" in code or "c = ( a + b )" in code.replace(" ", "")

    def test_generate_complex_expression(self, language, complex_valid_tokens):
        """Test generating code for complex nested expressions."""
        parser = Parser(language, complex_valid_tokens)
        result = parser.parse_with_ast()

        generator = PythonGenerator()
        code = generator.generate(result.ast)

        # Check for the complex expression structure
        assert "bba" in code
        assert "=" in code
        assert "b2a" in code
        assert "*" in code
        assert "+" in code

    def test_generate_print_statement(self, language):
        """Test generating print statements."""
        tokens = [
            "program",
            "abc",
            ";",
            "var",
            "a",
            ":",
            "integer",
            ";",
            "begin",
            "a",
            "=",
            "5",
            ";",
            "print",
            "(",
            "a",
            ")",
            ";",
            "end",
        ]
        parser = Parser(language, tokens)
        result = parser.parse_with_ast()

        generator = PythonGenerator()
        code = generator.generate(result.ast)

        assert "print(a)" in code

    def test_generate_print_with_label(self, language):
        """Test generating print statement with label."""
        tokens = [
            "program",
            "abc",
            ";",
            "var",
            "a",
            ":",
            "integer",
            ";",
            "begin",
            "a",
            "=",
            "5",
            ";",
            "print",
            "(",
            '"value=",',
            "a",
            ")",
            ";",
            "end",
        ]
        parser = Parser(language, tokens)
        result = parser.parse_with_ast()

        generator = PythonGenerator()
        code = generator.generate(result.ast)

        assert 'print(f"value=' in code
        assert "{a}" in code or "{a}" in code.replace(" ", "")

    def test_generated_code_is_valid_python(self, language, simple_valid_tokens):
        """Test that generated code is syntactically valid Python."""
        parser = Parser(language, simple_valid_tokens)
        result = parser.parse_with_ast()

        generator = PythonGenerator()
        code = generator.generate(result.ast)

        # Try to compile it
        try:
            compile(code, "<string>", "exec")
            is_valid = True
        except SyntaxError:
            is_valid = False

        assert is_valid, f"Generated code is not valid Python:\n{code}"

    def test_generated_code_executes(self, language, simple_valid_tokens):
        """Test that generated code can be executed."""
        parser = Parser(language, simple_valid_tokens)
        result = parser.parse_with_ast()

        generator = PythonGenerator()
        code = generator.generate(result.ast)

        # Try to execute it
        try:
            exec(code)
            can_execute = True
        except Exception as e:
            can_execute = False
            error = e

        assert (
            can_execute
        ), f"Generated code failed to execute: {error if not can_execute else ''}"
